# kubectl create deployment workpress --image=wordpress:4.8-apache --dry-run -o yaml > wordpress_deployment.yml 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service:3306 
        - name: WOLDPRESS_DB_PASSWORD
          value: "102030"
        ports:
        - name: http-port
          containerPort: 80
